import { DomainNode, TechnologyArea, ResearchTopic, ProjectItem, AsmitaTrack } from './types';

export const DOMAINS: DomainNode[] = [
  {
    id: 'ai',
    name: 'AI',
    category: 'Artificial Intelligence',
    shortDesc: 'Artificial intelligence and machine learning.',
    details: 'Developing foundational models, perceptual reasoning engines, and adaptive reinforcement architectures designed to navigate high-dimensional physical and analytical states.',
    color: '#38bdf8',
    connections: ['computing', 'robotics', 'health', 'education'],
  },
  {
    id: 'computing',
    name: 'COMPUTING',
    category: 'Computer Architecture & Systems',
    shortDesc: 'Computer architecture, software systems and semiconductor technology.',
    details: 'Architecting ultra-low-latency heterogeneous systems, energy-efficient spatial accelerators, and deterministic compiler fabrics for real-time workload orchestration.',
    color: '#818cf8',
    connections: ['ai', 'robotics', 'health'],
  },
  {
    id: 'robotics',
    name: 'ROBOTICS',
    category: 'Autonomous Physical Systems',
    shortDesc: 'Intelligent machines, automation and human-machine systems.',
    details: 'Synthesizing inverse kinematic solvers, closed-loop tactile feedback, sub-millimeter actuator control, and spatial telemetry for autonomous physical interaction.',
    color: '#34d399',
    connections: ['ai', 'computing', 'health'],
  },
  {
    id: 'health',
    name: 'HEALTH',
    category: 'Biomedical & Computational Biology',
    shortDesc: 'Biomedical technology, computational biology and health innovation.',
    details: 'Applying computational genomics, biophysical simulation, molecular dynamic modeling, and precision surgical instrumentation to elevate human clinical outcomes.',
    color: '#f472b6',
    connections: ['ai', 'computing', 'robotics'],
  },
  {
    id: 'education',
    name: 'EDUCATION',
    category: 'Asmita Talent Engine',
    shortDesc: 'Building the next generation of technical talent.',
    details: 'Through our dedicated Asmita division, instilling rigorous technical fundamentals, professional mastery, and applied engineering systems in future pioneers.',
    color: '#fbbf24',
    connections: ['ai', 'computing', 'robotics'],
  },
];

export const TECHNOLOGIES: TechnologyArea[] = [
  {
    id: 'ai',
    title: 'Artificial Intelligence',
    tagline: 'Perception, Reasoning & Mathematical Generalization',
    description: 'Machine learning, intelligent systems, computer vision and AI-driven software engineered for deterministic reliability in complex real-world environments.',
    bulletPoints: [
      'Self-supervised representation learning for sensory streams',
      'Neuro-symbolic reasoning frameworks with provable constraints',
      'Real-time edge inference with sub-millisecond execution envelopes',
      'Robust multimodal perception under sensory degradation',
    ],
    techMetrics: [
      { label: 'Latency Envelope', value: '< 2.4 ms' },
      { label: 'Model Modality', value: 'Audio / Vision / Kinematics' },
      { label: 'Verification', value: 'Formal Safety Bounds' },
    ],
    interactiveType: 'ai',
  },
  {
    id: 'robotics',
    title: 'Robotics',
    tagline: 'Physical Embodiment & Dynamic Actuation',
    description: 'Robotic systems, autonomous machines, human-machine interaction and advanced control systems capable of translating computational decisions into physical force.',
    bulletPoints: [
      'Multi-axis inverse kinematics and dynamic trajectory synthesis',
      'High-bandwidth impedance and admittance control loops',
      'Haptic and micro-tactile surface perception arrays',
      'Shared human-in-the-loop collaborative autonomy',
    ],
    techMetrics: [
      { label: 'Actuation Frequency', value: '1.2 kHz' },
      { label: 'Spatial Repeatability', value: '± 0.015 mm' },
      { label: 'Degrees of Freedom', value: '7-DOF Redundant' },
    ],
    interactiveType: 'robotics',
  },
  {
    id: 'computing',
    title: 'Computing',
    tagline: 'Silicon Architectures & Scalable Fabrics',
    description: 'Software engineering, computer architecture, semiconductor technology and high-performance computing driving unprecedented energy efficiency.',
    bulletPoints: [
      'Domain-specific accelerator architectures for tensor computation',
      'Deterministic memory hierarchies and memory-wall mitigation',
      'Heterogeneous compute clusters with direct-to-silicon compilation',
      'Micro-architectural resilience against physical fault states',
    ],
    techMetrics: [
      { label: 'Energy Metric', value: '0.85 pJ/op' },
      { label: 'Interconnect Bandwidth', value: '1.6 Tbps' },
      { label: 'Instruction Pipeline', value: 'Speculative RISC-V' },
    ],
    interactiveType: 'computing',
  },
  {
    id: 'biomedical',
    title: 'Biomedical Technology',
    tagline: 'Computational Biology & Clinical Systems',
    description: 'Computational biology, genomics, health technology and emerging biomedical systems transforming cellular insights into life-saving clinical tools.',
    bulletPoints: [
      'Algorithmic genomic variant assembly and transcriptomics',
      'High-throughput structural molecular docking models',
      'Sub-millimeter micro-actuated surgical end-effectors',
      'Continuous physiological telemetry and predictive biomarkers',
    ],
    techMetrics: [
      { label: 'Resolution', value: 'Single-Cell Spatial' },
      { label: 'Docking Throughput', value: '4.8M cmpds/hr' },
      { label: 'Sensor Fidelity', value: 'Sub-Femtoampere' },
    ],
    interactiveType: 'health',
  },
];

export const RESEARCH_TOPICS: ResearchTopic[] = [
  {
    id: 'ai-ml',
    title: 'AI & Machine Learning',
    category: 'Intelligence',
    description: 'Investigating foundational representation learning, inductive bias optimization, and causal inference in high-entropy physical systems.',
    researchQuestions: [
      'How can representation learning guarantee invariant spatial understanding across radical sensor noise?',
      'Can symbolic reasoning engines be coupled with continuous neural embeddings without catastrophic forgetting?',
    ],
    currentStatus: 'Active Investigation',
    relatedTechnologies: ['Transformer Architectures', 'Causal Graphs', 'Dynamic Neural Fields'],
    investigationLead: 'Autonomous Intelligence Group',
    facility: 'Lab Alpha — Core Mathematics',
  },
  {
    id: 'robotics-control',
    title: 'Robotics & Control',
    category: 'Robotics',
    description: 'Formulating adaptive nonlinear control theories and whole-body compliance for dynamic locomotion and high-load manipulators.',
    researchQuestions: [
      'How do we eliminate stability divergence during non-smooth contact transitions in complex terrains?',
      'What are the optimal balance controllers under unknown variable payload disturbances?',
    ],
    currentStatus: 'Experimental Validation',
    relatedTechnologies: ['Model Predictive Control', 'Hamiltonian Dynamics', 'Series Elastic Actuators'],
    investigationLead: 'Robotic Dynamics Lab',
    facility: 'Lab Beta — Actuation Testbed',
  },
  {
    id: 'surgical-robotics',
    title: 'Surgical Robotics',
    category: 'Medical Robotics',
    description: 'Developing ultra-precise multi-axis surgical robotic arms capable of tremor eradication, autonomous micro-suturing, and sub-millimeter stereotaxis.',
    researchQuestions: [
      'What level of haptic feedback fidelity is required for micro-vascular anastomoses via teleoperation?',
      'How can multi-spectral computer vision automatically delineate tumor margins in real-time incision paths?',
    ],
    currentStatus: 'Pre-Clinical Stage',
    relatedTechnologies: ['Cable-Driven Articulation', 'Stereotaxic Navigation', 'Real-time Optical Coherence'],
    investigationLead: 'Bio-Surgical Engineering Team',
    facility: 'Lab Gamma — Precision Surgical Suite',
  },
  {
    id: 'computer-architecture',
    title: 'Computer Architecture',
    category: 'Computing',
    description: 'Exploring non-von Neumann computing topologies, near-memory processing, and specialized execution pipelines for sparse graph workloads.',
    researchQuestions: [
      'Can near-data compute units reduce memory bus energy dissipation by an order of magnitude for graph analytics?',
      'What hardware scheduler minimizes pipeline stall latency for irregular sparse tensor networks?',
    ],
    currentStatus: 'Laboratory Prototyping',
    relatedTechnologies: ['Near-Memory Compute', 'RISC-V Vector Extensions', 'Asynchronous Logic'],
    investigationLead: 'Silicon Systems Architecture',
    facility: 'Lab Delta — Microarchitecture Studio',
  },
  {
    id: 'semiconductor',
    title: 'Semiconductor Technology',
    category: 'Semiconductors',
    description: 'Simulating quantum transport phenomena in sub-2nm node geometries, wide-bandgap power semiconductors, and monolithic 3D heterogeneous stacking.',
    researchQuestions: [
      'How can thermal gradient extraction be stabilized across 3D-stacked silicon dies with non-uniform power density?',
      'What material interfaces minimize interface trap density in next-generation GaN power switches?',
    ],
    currentStatus: 'Active Investigation',
    relatedTechnologies: ['GAAFET Modeling', 'Wide Bandgap GaN/SiC', 'Heterogeneous Dielet Packaging'],
    investigationLead: 'Advanced Semiconductor Group',
    facility: 'Nanofabrication Simulation Lab',
  },
  {
    id: 'computational-biology',
    title: 'Computational Biology',
    category: 'Health & Biology',
    description: 'Simulating complex cellular macromolecular machinery and metabolic networks using coarse-grained molecular dynamics.',
    researchQuestions: [
      'Can deep generative diffusion models accurately predict allosteric conformational shifts in transmembrane receptors?',
      'How can spatial transcriptomic data predict tissue-level regenerative trajectory?',
    ],
    currentStatus: 'Active Investigation',
    relatedTechnologies: ['Molecular Dynamics', 'Equivariant Neural Networks', 'Massively Parallel Solver'],
    investigationLead: 'Computational Biosystems',
    facility: 'Biocomputing Cluster Node',
  },
  {
    id: 'genomics',
    title: 'Genomics',
    category: 'Health & Biology',
    description: 'High-throughput algorithmic sequence assembly, structural variant phasing, and deep epigenetic profiling.',
    researchQuestions: [
      'How can long-read sequencing noise be computationally resolved to attain Q60 accuracy in complex genomic repeats?',
      'What regulatory chromatin loop modifications correlate most strongly with acquired treatment resistance?',
    ],
    currentStatus: 'Experimental Validation',
    relatedTechnologies: ['Long-Read Alignment', 'Graph Genomes', 'Epigenetic Methylation Callers'],
    investigationLead: 'Genomic Informatics Core',
    facility: 'Genomics Data Vault',
  },
  {
    id: 'health-innovation',
    title: 'Health Innovation',
    category: 'Health & Biology',
    description: 'Engineering non-invasive bio-sensing arrays, wearable hemodynamic monitors, and closed-loop therapeutic release devices.',
    researchQuestions: [
      'Can transdermal optical interferometry non-invasively measure continuous arterial stiffness changes in real time?',
      'What closed-loop control architecture prevents over-correction in automated bio-hormonal delivery?',
    ],
    currentStatus: 'Laboratory Prototyping',
    relatedTechnologies: ['Microfluidic Sensors', 'Optical Interferometry', 'Edge Biomarker Processors'],
    investigationLead: 'Translational Health Devices',
    facility: 'Translational Engineering Suite',
  },
  {
    id: 'human-machine-systems',
    title: 'Human-Machine Systems',
    category: 'Interaction',
    description: 'Designing high-bandwidth neural-assistive interfaces, ergonomic exoskeleton kinematics, and intention-prediction algorithms.',
    researchQuestions: [
      'What latent motor intention signals can be extracted from surface EMG arrays with under 15ms latency?',
      'How does continuous haptic guidance alter cognitive load and motor skill acquisition curves in technical tasks?',
    ],
    currentStatus: 'Active Investigation',
    relatedTechnologies: ['High-Density EMG', 'Adaptive Haptic Exoskeletons', 'Cognitive Load Telemetry'],
    investigationLead: 'Human Augmentation Division',
    facility: 'Cybernetics & Ergonomics Lab',
  },
];

export const PROJECTS: ProjectItem[] = [
  {
    id: 'proj-surgical-robotics',
    name: 'Surgical Robotics Platform',
    category: 'Robotics & Health',
    oneLiner: 'Robotic systems for precision manipulation and sub-millimeter stereotaxis.',
    description: 'An advanced teleoperated robotic surgical platform translating computational spatial trajectory planning into physical needle and end-effector articulation with active tremor filtration and haptic boundary enforcement.',
    technologyStack: ['Real-Time Linux (PREEMPT_RT)', 'C++20 Kinematics Engine', 'FPGA Motor Controllers', 'Sub-Micron Optical Encoders', 'Stereo Vision HUD'],
    status: 'Development',
    specs: [
      { label: 'Positioning Accuracy', value: '± 0.02 mm' },
      { label: 'Control Loop Frequency', value: '2,000 Hz' },
      { label: 'Joint Articulation', value: '7-DOF Manipulator' },
      { label: 'Latency', value: '< 3.8 ms End-to-End' },
    ],
  },
  {
    id: 'proj-intelligent-systems',
    name: 'Intelligent Systems Architecture',
    category: 'Artificial Intelligence',
    oneLiner: 'AI systems capable of reasoning, perception and decision-making under uncertainty.',
    description: 'A modular software and mathematical engine fusing self-supervised sensory representations with formal constraint checkers to govern mission-critical physical operations without hallucinations.',
    technologyStack: ['PyTorch / JAX', 'C++ Tensor Runtime', 'Symbolic SMT Solvers', 'Zero-Copy Shared Memory', 'Distributed IPC'],
    status: 'Prototype',
    specs: [
      { label: 'Inference Throughput', value: '850 fps @ 4K' },
      { label: 'Safety Verification', value: 'SMT-Provable Bounds' },
      { label: 'Quantization', value: 'FP8 / INT4 Hybrid' },
      { label: 'Footprint', value: 'Edge-Deployable' },
    ],
  },
  {
    id: 'proj-advanced-computing',
    name: 'Advanced Computing Accelerator',
    category: 'Computing & Hardware',
    oneLiner: 'Exploration of energy-efficient computing architectures and spatial pipelines.',
    description: 'A domain-tailored heterogeneous processor architecture optimized for high-bandwidth sparse tensor contractions and dynamic graph neural routing, bypassing classical memory-bandwidth bottlenecks.',
    technologyStack: ['SystemVerilog / Chisel', 'RISC-V ISA Core', 'HBM3 Interconnect', 'LLVM Compiler Backend', 'Cycle-Accurate Simulator'],
    status: 'Research',
    specs: [
      { label: 'Efficiency Target', value: '18.4 TOPS/Watt' },
      { label: 'Memory Bus Width', value: '1024-bit Wide' },
      { label: 'Silicon Target', value: 'FinFET / GAAFET' },
      { label: 'Architecture Type', value: 'Spatial Dataflow' },
    ],
  },
  {
    id: 'proj-health-intelligence',
    name: 'Health Intelligence Biosuite',
    category: 'Biomedical & Genomics',
    oneLiner: 'Technology at the intersection of computation, genomics and biology.',
    description: 'An integrated computational platform executing automated genomic variant interpretation, molecular binding energy simulation, and clinical telemetry stream analysis for precision intervention.',
    technologyStack: ['Rust Bio-Core', 'CUDA Molecular Solvers', 'GraphQL Clinical API', 'Micro-Telemetry Firmware', 'Dockerized Compute'],
    status: 'Development',
    specs: [
      { label: 'Sequencing Throughput', value: '120 Gbases/run' },
      { label: 'Variant Call Accuracy', value: '99.98% Precision' },
      { label: 'Data Ingestion Rate', value: '50,000 pts/sec' },
      { label: 'Compliance', value: 'HIPAA & ISO 27001' },
    ],
  },
  {
    id: 'proj-autonomous-locomotion',
    name: 'Dynamic Locomotion Framework',
    category: 'Robotics',
    oneLiner: 'Robust non-flat terrain locomotion with high-frequency predictive impedance control.',
    description: 'A quadrupedal and bipedal mechanical control framework utilizing dynamic model-predictive control and real-time lidar elevation maps to achieve self-stabilizing gait over unstable surfaces.',
    technologyStack: ['C++ Dynamics Engine', 'Micro-ROS', 'Custom BLDC Drivers', 'EtherCAT Bus', 'Gazebo & Drake Physics'],
    status: 'Prototype',
    specs: [
      { label: 'Update Cycle', value: '1.0 kHz' },
      { label: 'Payload Capacity', value: '35 kg' },
      { label: 'Terrain Roughness', value: 'Class IV Obstacles' },
      { label: 'Recovery Time', value: '< 120 ms' },
    ],
  },
  {
    id: 'proj-asmita-learning-engine',
    name: 'Asmita Adaptive Learning Engine',
    category: 'Education Technology',
    oneLiner: 'Rigorous cognitive tracking and problem decomposition engine for professional learners.',
    description: 'An educational intelligence platform structuring complex accounting, regulatory, and computer engineering curricula into deterministic concept dependency graphs with adaptive diagnostic mastery.',
    technologyStack: ['TypeScript / Next.js', 'Knowledge Graph Engine', 'PostgreSQL / Vector DB', 'WebAssembly Compilers'],
    status: 'Product',
    specs: [
      { label: 'Concept Graph Nodes', value: '14,200+' },
      { label: 'Evaluation Precision', value: 'Sub-concept Level' },
      { label: 'Active Cohort Use', value: 'Enterprise Ready' },
      { label: 'Course Domains', value: 'CA, CS, CWA, Tech' },
    ],
  },
];

export const ASMITA_TRACKS: AsmitaTrack[] = [
  {
    code: 'CA',
    title: 'Chartered Accountancy',
    subtitle: 'Financial Engineering & Corporate Governance',
    description: 'Deep mastery of advanced financial reporting, strategic financial management, corporate tax planning, and systemic risk auditing.',
    modules: [
      'Financial Reporting & Ind AS Standards',
      'Advanced Auditing & Forensic Assurance',
      'Strategic Financial Management (SFM)',
      'Direct & Indirect Tax Laws & Policy',
    ],
    focus: 'Institutional finance, audit precision, and regulatory governance.',
  },
  {
    code: 'CS',
    title: 'Company Secretary',
    subtitle: 'Corporate Laws, Compliance & Capital Markets',
    description: 'Comprehensive study of corporate restructuring, securities laws, compliance governance, board processes, and multi-jurisdictional legal mechanics.',
    modules: [
      'Company Law & Secretarial Practice',
      'Securities Law & Capital Market Operations',
      'Corporate Restructuring & Insolvency (IBC)',
      'Governance, Risk Management & Ethics',
    ],
    focus: 'Legal architecture, boardroom governance, and statutory oversight.',
  },
  {
    code: 'CWA',
    title: 'Cost & Management Accounting',
    subtitle: 'Operational Efficiency & Strategic Cost Analysis',
    description: 'Strategic analysis of enterprise cost structures, operational efficiency optimization, valuation modeling, and performance management.',
    modules: [
      'Strategic Performance Management',
      'Cost & Financial Analysis of Systems',
      'Corporate Financial Restructuring',
      'Supply Chain Costing & Quantitative Analysis',
    ],
    focus: 'Operational economics, capital optimization, and management analytics.',
  },
  {
    code: 'TECH',
    title: 'Technology Education',
    subtitle: 'Computer Science, Systems & Emerging Technologies',
    description: 'Practical, rigorous grounding in algorithms, modern systems engineering, computer architecture, distributed computing, and artificial intelligence.',
    modules: [
      'Systems Programming & Memory Management',
      'Algorithms, Data Structures & Complexity',
      'Computer Architecture & Operating Systems',
      'Machine Learning & Applied Intelligent Systems',
    ],
    focus: 'Core engineering discipline, first-principles computing, and technical literacy.',
  },
];

export const VENTURE_PILLARS = [
  {
    phase: '01',
    name: 'Research',
    title: 'Explore difficult technical problems',
    description: 'We do not chase transient software trends. We identify fundamental scientific and engineering hurdles in intelligence, materials, computing, and biology where breakthroughs produce generational value.',
    deliverables: ['First-principles mathematical models', 'Experimental lab benchmarks', 'Patentable architectural topologies', 'Rigorous peer verification'],
  },
  {
    phase: '02',
    name: 'Build',
    title: 'Turn ideas into working systems',
    description: 'Theory must withstand physical reality. Our engineers translate experimental models into rugged, validated hardware prototypes, embedded firmware, and deterministic software engines.',
    deliverables: ['Functional physical prototypes', 'Sub-millimeter actuation systems', 'Custom silicon RTL & testbenches', 'End-to-end integration testbeds'],
  },
  {
    phase: '03',
    name: 'Scale',
    title: 'Transform successful technology into products and ventures',
    description: 'When prototypes prove reliable, we spin out dedicated ventures, engineer production-grade supply chains, and deploy systems into medical centers, research facilities, and global industry.',
    deliverables: ['Dedicated venture capitalization', 'Regulatory compliance & validation', 'Industrial manufacturing handoff', 'Global operational deployment'],
  },
];

export const COMPANY_VALUES = [
  {
    title: 'Curiosity',
    subtitle: 'Question assumptions.',
    description: 'True breakthroughs never arrive from accepted consensus. We interrogate first principles and question standard engineering constraints to discover unconventional solutions.',
  },
  {
    title: 'Engineering',
    subtitle: 'Build with precision.',
    description: 'Scientific insight is only as potent as the engineering that realizes it. We prize mathematical rigor, sub-millimeter tolerances, and deterministic reliability.',
  },
  {
    title: 'Research',
    subtitle: 'Understand before scaling.',
    description: 'We reject premature scaling of fragile prototypes. We invest heavily in fundamental theoretical and physical validation before committing to manufacturing.',
  },
  {
    title: 'Impact',
    subtitle: 'Technology should matter in the real world.',
    description: 'We measure success not by speculative hype, but by tangible real-world outcome: surgical precision elevated, computing power democratized, human talent amplified.',
  },
  {
    title: 'Education',
    subtitle: 'Knowledge compounds when shared.',
    description: 'Through Asmita, we actively cultivate the next generation of engineers, technologists, and governance leaders. Lasting innovation requires enduring talent.',
  },
];
